### ISSUE TITLE
Check the Extension OpenCage

### ISSUE THREAD

**Issue by milumelissa** [Noznoc/breathe-easy#3]
[Breathe Easy.xlsx](https://github.com/Noznoc/breathe-easy-test/files/4995366/Breathe.Easy.xlsx)

**Comment by Noznoc** [comment]
OpenCage requires an API Key, I'm trying to avoid the number of keys we need to keep track of for this map. For now the only suggestion I have to include place name is show the labels more prominently on the basemap.
